* Tree-sitter-tiger

This is a simplest tree-sitter implementation for Tiger Language from Appel's
/Modern Compiler Implementation/, based on the [[https://www.cambridge.org/core/books/modern-compiler-implementation-in-ml/appendix-tiger-language-reference-manual/][reference manual]].

** Using the tree-sitter

If you are using Emacs, you can use the [[https://github.com/tiger-compiler-collection/tiger-ts-mode][tiger-ts-mode]] and download the latest
release from this repository.

** Expression grammar (0.1.2)

Version 0.1.2 uses a layered expression grammar to enforce operator precedence
and associativity. From highest to lowest precedence: unary minus, ~*~ and ~/~,
~+~ and ~-~, comparisons (~=~, ~<>~, ~<~, ~<=~, ~>~, ~>=~), ~&~, and ~|~.
Arithmetic and boolean binary operators are left-associative.

Comparisons are non-associative: ~a < b < c~ is a syntax error. Parentheses are
required to compare the result of another comparison, as in ~(a < b) < c~ or
~a < (b < c)~. This is enforced by the grammar without a yacc-style ~%nonassoc~
directive.

Queries using the old expression node names need to be updated:

- ~arithmetic_expr~ is now ~add_expression~ or ~mul_expression~.
- ~compare_expr~ is now ~compare_expression~.
- ~boolean_expr~ is now ~and_expression~ or ~or_expression~.

** String literals

String literals support formatting escapes: one or more spaces, tabs, newlines,
carriage returns, or formfeeds enclosed by backslashes.

** License

LGPL-3.0-or-later.  See [[file:LICENSE][LICENSE]] for LGPL v3 and [[file:COPYING][COPYING]] for the accompanying GPL v3 terms.
